services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./:/usr/app
      - /usr/app/node_modules

volumes:
  mariadb_data:
